USE ROLE T_E_dlt_role;

USE DATABASE ENGINEER_ADS;
USE WAREHOUSE DEV_WH;
USE SCHEMA STAGING;

SELECT * FROM engineer_field_job_ads LIMIT 5;

SELECT DESCRIPTION__TEXT FROM engineer_field_job_ads LIMIT 10;

SELECT OCCUPATION_GROUP__LABEL FROM engineer_field_job_ads LIMIT 10;