--##### DLT ROLE #####;
---------------------------------------------------------------------------

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS T_E_dlt_role;

USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE T_E_dlt_role;

GRANT USAGE ON DATABASE ENGINEER_ADS TO ROLE T_E_dlt_role;

GRANT USAGE ON SCHEMA ENGINEER_ADS.Staging TO ROLE T_E_dlt_role;

GRANT CREATE TABLE ON SCHEMA ENGINEER_ADS.Staging TO ROLE T_E_DLT_ROLE;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ENGINEER_ADS.Staging TO ROLE T_E_DLT_ROLE;

GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ENGINEER_ADS.Staging TO ROLE T_E_DLT_ROLE;

SHOW GRANTS TO ROLE T_E_DLT_ROLE;

GRANT ROLE T_E_DLT_ROLE TO USER T_E_DLT;


--###Testing ###;

USE ROLE T_E_DLT_ROLE;

USE WAREHOUSE DEV_WH;

SHOW DATABASES;

USE DATABASE ENGINEER_ADS;

SHOW SCHEMAS;

CREATE TABLE IF NOT EXISTS Staging.test(
    test INTEGER PRIMARY KEY
);

INSERT INTO staging.test (test) 
VALUES(2);

DROP TABLE staging.test;
