---------------------------------------------------------------------------
--##### DBT ROLE #####;
---usage on warehouse

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS T_E_dbt_role;

USE ROLE SECURITYADMIN;

GRANT ROLE T_E_DLT_ROLE TO ROLE T_E_dbt_role;

SHOW GRANTS TO ROLE T_E_DBT_ROLE;

GRANT USAGE ON SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;

GRANT CREATE TABLE ON SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;

GRANT CREATE VIEW ON SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;


GRANT SELECT, INSERT, UPDATE, DELETE ON ALL VIEWS IN SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE VIEWS IN SCHEMA ENGINEER_ADS.Warehouse TO ROLE T_E_DBT_ROLE;

GRANT ROLE T_E_DBT_ROLE TO USER T_E_DBT;


--##TESTING

SHOW GRANTS ON SCHEMA ENGINEER_ADS.WAREHOUSE;

USE ROLE T_E_DBT_ROLE;

CREATE TABLE IF NOT EXISTS Warehouse.test(
    test INTEGER PRIMARY KEY
);

SHOW TABLES IN Warehouse;

INSERT INTO warehouse.test (test) 
VALUES(2);

SELECT * FROM warehouse.test;

DROP TABLE warehouse.test;


--##usage on marts

GRANT USAGE ON SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;

GRANT CREATE TABLE ON SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;

GRANT CREATE VIEW ON SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;


GRANT SELECT, INSERT, UPDATE, DELETE ON ALL VIEWS IN SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE VIEWS IN SCHEMA ENGINEER_ADS.marts TO ROLE T_E_DBT_ROLE;






