USE ROLE SYSADMIN;

USE WAREHOUSE DEV_WH;

CREATE DATABASE IF NOT EXISTS Engineer_ads;

USE DATABASE ENGINEER_ADS;

CREATE SCHEMA IF NOT EXISTS Staging;

CREATE SCHEMA IF NOT EXISTS Warehouse;

CREATE SCHEMA IF NOT EXISTS Marts;