models:
  - name: mart_job_listings
    description: "Den här tabellen innehåller information om jobbannonser."
    data_tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ["headline", "vacancies", "salary_type", "relevance", "employer_name", "workplace_city", "description",
           "duration", "scope_of_work_min", "scope_of_work_max", "deadline", "engineer_type", "published"]
    columns:
      - name: vacancies
        description: "Antal lediga platser på jobbannonsen"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .90
              min_value: 1 
              max_value: 30

      - name: headline
        description: "Rubrik för jobbannonsen"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_have_consistent_casing:
              display_inconsistent_columns: true

      - name: salary_type
        description: "Lönetyp"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Fast månads- vecko- eller timlön', 'Fast och rörlig lön', 'Rörlig ackords- eller provisionslön']

      - name: relevance
        description: "Relevans för jobbannonsen"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float

      - name: employer_name
        description: "Arbetsgivarens namn"
        data_tests:
          - not_null

      - name: workplace_city
        description: "Arbetsplatsens stad"
        data_tests:
          - not_null

      - name: description
        description: "Beskrivning av jobbannonsen"
        data_tests:
          - not_null

      - name: duration
        description: "Längd på anställning"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['3 månader – upp till 6 månader', '11 dagar - upp till 3 månader', 'Upp till 10 dagar', 'Tills vidare', '6 månader eller längre', 'Not Available']

      - name: scope_of_work_min
        description: "Minst antal timmar per vecka"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Not Available', '25', '100', '0']

      - name: scope_of_work_max
        description: "Max antal timmar per vecka"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Not Available', '100']

      - name: deadline
        description: "Sista ansökningsdag för jobbannonsen"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp_ntz

      - name: published
        description: "Publiceringsdatum för jobbannonsen"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp_ntz

      - name: engineer_type
        description: "Ingenjörstyp"
        data_test:
            - not_null
            - dbt_expectations.expect_column_values_to_be_in_set:
                value_set: ["Rymdingenjör", "Driftingenjör", "Automationsingenjör", "Högskoleingenjör", "Civilingenjör", "Maskiningenjör", "Miljöingenjör"]
            - dbt_expectations.expect_column_values_to_have_consistent_casing:
                display_inconsistent_columns: true

version: 2

macros:
  - name: capitalize_first_letter_each_word   
    description: "Detta makro gör att den första bokstaven i varje ord i en angiven kolumn blir versal. Det hanterar null-värden genom att returnera null."
    arguments:
      - name: column
        type: string
        description: "Kolumnen vars ord du vill göra versala."
    returns:
      type: string
      description: "Den angivna kolumnen med versala första bokstäver i varje ord."

