models:
  - name: dim_auxillary_attribute
    description: "Auxillary attributes for job ads"
    data_tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ["auxillary_attribute_id", "required_driving_license", "experience_required", "access_to_own_car"]

    columns: 
      - name: auxillary_attribute_id
        description: "Unique identifier for the auxillary attribute"
        data_tests:
        - not_null
        - unique

      - name: required_driving_license
        description: "Indicates if a driving license is required for the job"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          
      - name: experience_required
        description: "Indicates if experience is required for the job" 
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
    
   
      - name: access_to_own_car
        description: "Indicates if access to own car is required for the job"
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
   
   