models:
  - name: dim_auxillary_attribute
    description: "Information om krav och önskemål för jobb, innehåller information om krav på körkort, erfarenhet, tillgång till egen bil, se nedan för mer information."
    data_tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ["auxillary_attribute_id", "required_driving_license", "experience_required", "access_to_own_car"]

    columns: 
      - name: auxillary_attribute_id
        description: "Primärnyckel, unik identifierare för krav och önskemål för jobb, surrogatnyckel skapad baserat på kolumnerna id, required_driving_license, experience_required och access_to_own_car."
        data_tests:
          - unique
          - not_null

      - name: required_driving_license
        description: "Krav på körkort."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          
      - name: experience_required
        description: "Krav på erfarenhet."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
    
   
      - name: access_to_own_car
        description: "Krav på tillgång till egen bil."
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
   
   