models: 
  - name: dim_auxillary_attribute
    data_tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ["auxillary_attribute_id", "required_driving_license", "experience_required", "access_to_own_car"]

    columns: 
      - name: auxillary_attribute_id
        data_tests:
          - unique
          - not_null

      - name: required_driving_license
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          
      - name: experience_required
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
    
   
      - name: access_to_own_car
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: [TRUE, FALSE]
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
   
   