sources:
  - name: engineer_ads
    description: "Ingenjörsjobb från Arbetsförmedlingen"
    schema: Staging
    tables:
      - name: stg_data_ads
        description: "Ingenjörsjobb från Arbetsförmedlingen"
        identifier: engineer_field_job_ads