Table fct_job_ad {
    job_id STRING [primary key]
    number_of_vacancies INTEGER [NOT NULL]
    relevance INTEGER [NOT NULL]
    application_deadline DATETIME [NOT NULL]
    publication_date DATETIME [NOT NULL]
    job_details_key STRING [ref: > dim_job_detail.job_detail_id]
    employer_key STRING [ref: > dim_employer.employer_id]
    auxillary_key STRING [ref: > dim_auxillary_attribute.auxillary_id]
    }

Table dim_job_detail {
    job_detail_id STRING [primary key]
    headline STRING [NOT NULL]
    description STRING [NOT NULL]
    description_html_formatted STRING [NOT NULL]
    employement_type STRING [NOT NULL]
    duration STRING [NOT NULL]
    salary_type STRING [NOT NULL]
    scope_of_work_min NUMBER(3,0) [NOT NULL]
    scope_of_work_max NUMBER(3,0) [NOT NULL]
    engineer_type STRING [NOT NULL]
    occupation_label STRING [NOT NULL]
}

Table dim_employer {
    employer_id STRING [primary key]
    employer_name STRING [NOT NULL]
    employer_organization_number STRING [NOT NULL]
    workplace_street_address STRING [NOT NULL]
    workplace_region STRING [NOT NULL]
    workplace_postcode STRING [NOT NULL]
    workplace_city STRING [NOT NULL]
    workplace_country STRING [NOT NULL]
    workplace_municipality STRING [NOT NULL]
}

Table dim_auxillary_attribute {
    auxillary_id STRING [primary key]
    experience_required VARCHAR(30) [NOT NULL]
    driver_license VARCHAR(30) [NOT NULL]
    access_to_own_car VARCHAR(30) [NOT NULL]
}